### ISSUE TITLE
if timer test wrong in stm32l4_timer.c

### ISSUE THREAD

**Issue by manitou48** [GrumpyOldPizza/arduino-STM32L4#1]
in stm32l4_timer.c, see
if ((timer->instance >= TIMER_INSTANCE_TIM2) && (timer->instance >= TIMER_INSTANCE_TIM7))

2nd condition should be <=

**Comment by GrumpyOldPizza** [comment]
Fixed. Nice catch.

https://github.com/GrumpyOldPizza/arduino-STM32L4/commit/e453ebe5adc75dca09ef120f8ae0a3a558bda575
