### ISSUE TITLE
Timer interrupts?

### ISSUE THREAD

**Issue by laterrps** [GrumpyOldPizza/arduino-STM32L4#17]
does exist any way for using timer interrrupts?

**Comment by GrumpyOldPizza** [comment]
Not as of right now.

What are you trying to do ?

- Thomas

**Comment by laterrps** [comment]
i would like to supervise certain tasks not using if(millis()%x==0) i would like to use timer interrupts.

**Comment by laterrps** [comment]
I have been watchin your code and i find out that you are using timers interrupts for dac converters and pwm , is it  too dificult to implement just timmer interrupst?

**Comment by GrumpyOldPizza** [comment]
My question was really more like what granularity you need.

The core itself uses internally 1ms timeouts, which you could use.

A Class API does not exist for that yet.

armv7m_timer_t myTimer;

armv7m_timer_create(&myTimer, (armv7m_timer_callback_t)myTimerCallback);

armv7m_timer_start(&myTimer, timeout);

armv7m_timer_stop(&myTimer);


N.b. those timers are one-shot, meaning you need to start the timer again
in "myTimerCallback". Ah, "timeout" is in milliseconds.

Hope that helps.

- Thomas

**Comment by kriswiner** [comment]
Or you could use RTC.Alarm but this would be for a 1 Hz or lower frequency
timer.

**Comment by laterrps** [comment]
Thank you very much i'll see it! 
best regards!!

**Comment by laterrps** [comment]
Thank you very much!!! it works!!! 


armv7m_timer_t myTimer;

armv7m_timer_create(&myTimer, (armv7m_timer_callback_t)myTimerCallback);

armv7m_timer_start(&myTimer, timeout);

armv7m_timer_stop(&myTimer);
