### ISSUE TITLE
How can i flash the ladybug stm32

### ISSUE THREAD

**Issue by laterrps** [GrumpyOldPizza/arduino-STM32L4#19]

**Comment by kriswiner** [comment]
Use the Arduino IDE?

**Comment by laterrps** [comment]
I would like to use Keil uvision

**Comment by kriswiner** [comment]
OK, go ahead...

**Comment by laterrps** [comment]
I meant i have user stm32f103 and i programmed it with an ftdi rs232 i just changed boot0 to high and boot1 to low , can I do something similar with your board?

**Comment by kriswiner** [comment]
Maybe. If you don;t want to use the Arduino IDE maybe better to use an
ST-Link.

**Comment by laterrps** [comment]
ok thank you very much! i will get one stlink! 
best regards

**Comment by laterrps** [comment]
I was usind arduino IDE but some times it is necessary to take a look deeper on registers values! so i have gone for keil uvision it have very interesting tools for debugging, I know that some times it is different or dificult when we are starting to use a new tool chain but algo some times it ir neccesari

**Comment by GrumpyOldPizza** [comment]
My workflow is to use the "Arduino IDE" to compile, and then "openocd" (which is part of the packge) along with gdb to debug.
