### ISSUE TITLE
does ladybug have read protection?

### ISSUE THREAD

**Issue by laterrps** [GrumpyOldPizza/arduino-STM32L4#20]
i have been trying to flash it and i cant

**Comment by kriswiner** [comment]
Little more information required.

Are you using the Arduino IDE?

Did you put it into boot mode first (press and hold boot, press and release
restart buttons)?

**Comment by laterrps** [comment]
I am using keil uvision and stlink v2

**Comment by GrumpyOldPizza** [comment]
Read protection is not enabled. I flash STM32L4 all the time using ST-Link V2. Never used Keil uVision, so perhaps it's just a setup question on your end.

N.b. the debugger cannot break in (and flashing) when the chip is in a low power mode. So pressing toggeling RESET while BOOT is pressed is a good way to get the chip into a good state.

**Comment by laterrps** [comment]
![image](https://user-images.githubusercontent.com/26884777/31513860-76f3019e-af44-11e7-9c31-68353a435546.png)

**Comment by laterrps** [comment]
![image](https://user-images.githubusercontent.com/26884777/31513898-94206630-af44-11e7-84b2-109f460735cd.png)

**Comment by laterrps** [comment]
can you help me?

**Comment by laterrps** [comment]
:/

**Comment by GrumpyOldPizza** [comment]
I have zero idea. Does the Arduino IDE work (which is what this github here is about) ?

**Comment by laterrps** [comment]
can you help me please?

**Comment by laterrps** [comment]
yes it is working!  on arduino ide

**Comment by GrumpyOldPizza** [comment]
Ok, so it's either an issue with the ST_Link adapter or the program you are using. Have you tried to update the firmware on the ST-Link (let's assume you have a cheap clone from ebay ...) ? Have you tried to flash this with the official ST ST-Link software to eliminate a Keil uVision problem ?

If it would be read out protected, the normally dfu-utils would throw an error, and the Arduino IDE would fail to flash a sketch.

**Comment by laterrps** [comment]
OK ok!!! I dont understand the reason because i can not to flash it!

**Comment by laterrps** [comment]
I have programmed now! but it is necessary to conect the rst pin in rst button, plus swdio swclk gnd and 3v3

**Comment by laterrps** [comment]
or how do you program it with st link?

**Comment by laterrps** [comment]
can you help me with a schematic?

**Comment by kriswiner** [comment]
There is a schematic on the Tindie page.

**Comment by laterrps** [comment]
i meant the schematic showing me how you programm it

**Comment by GrumpyOldPizza** [comment]
There should be a configuration option to use the internal reset via SWD.

**Comment by kriswiner** [comment]
Didn't you just say you did program it?

Can you program the Nucleo board or the discovery board?

Maybe the ST forum would be a better place. This site is for the Arduino
core.

**Comment by GrumpyOldPizza** [comment]
I am using SWDIO, SWCLK, GND and VCC.

**Comment by laterrps** [comment]
maybe is the programmer that i am using!! thank you very much!!! seriously!! you help me a lot!

**Comment by GrumpyOldPizza** [comment]
Well, we decided against exposing a RESET pin. Mainly because you can press
RESET manually, and for debugging a live system, the internal reset that
the debugger can trigger via SWD is good enough anyway.

**Comment by laterrps** [comment]
@GrumpyOldPizza  i have selecter some diferent options in keil uvision but only this work and i have to "make contact" with a jumper on the button reset pin 
![image](https://user-images.githubusercontent.com/26884777/31557865-62f5b0ae-afff-11e7-845c-a69cb3e7fb2d.png)

**Comment by laterrps** [comment]
@kriswiner  thank you i talked to you  because i consider you experts! and tank you very mucho for attend my questions! seriousle 
i am sorry if i am disturbing your work!!
best regards!

**Comment by laterrps** [comment]
@kriswiner  yes i have not problem with nucleo board now i am working with ladybug ! but i programmed it now, thank you very much

**Comment by clemaitre58** [comment]
@GrumpyOldPizza  which version of file do you send by ST-Link 32 V2 *.hex file or *.elf?
