### ISSUE TITLE
USB board on Dragonfly

### ISSUE THREAD

**Issue by arpeggio1234** [GrumpyOldPizza/arduino-STM32L4#24]
I am trying to compile an Arduino usb hostshield code and the compiler says ''please define board in avrpins.h''.
How can i do this, i am on Linux, manjaro, and found the avrpins.h file and see there is no 
STM32F4 entry, can i put it in, and yes what? Or can i use the teensy pinout in the code(how does one do that) for the dragonfly since they are lookalikes.
Is this the good place for this question or is there a better place to find answers for this kind of things. I am learning a lot of things especialy looking for answers and where to ask.
Thanks in advance, Dian from the Netherlands

**Comment by GrumpyOldPizza** [comment]
Dragonfly has it's own USB port. So why would you want to compile code for
it for a shield ?

Dragonfly also is STM32L4, not STM32F4.

**Comment by arpeggio1234** [comment]
Yeah you'r right it's the stm32L4,
the reason for usb is for usb in the to board, do you mean it can except usb in.
On my arduino's i am interfacing with this usb shield to a ps4 controller, very nice and then 
controlling the speak rate and bend(kind of filtering) of a speakjet chip.
So can i attach the ps4 controller direct to the Dragonfly board you think.
Any library names for usb in to stm32L4 board or sites to get more info on that issue.
Thanks for the reply and concern, sir.
Dian

**Comment by GrumpyOldPizza** [comment]
Ah, no. USB Host is not supported software wise with Dragonfly.

**Comment by arpeggio1234** [comment]
So do you have an idea how to implement the usb host lib to the stm31l4 board.
Include it in the avrpins.h.  do you knw, maybe how to overcome this issue.
Thanks again, Dian



----- Oorspronkelijk bericht -----
Van: Thomas Roell <notifications@github.com>
Aan: GrumpyOldPizza/arduino-STM32L4 <arduino-STM32L4@noreply.github.com>
Cc: arpeggio1234 <dianderocker@online.nl>, Author <author@noreply.github.com>
Verzonden: Sun, 19 Nov 2017 17:01:15 +0100 (CET)
Onderwerp: Re: [GrumpyOldPizza/arduino-STM32L4] USB board on Dragonfly (#24)

Ah, no. USB Host is not supported software wise with Dragonfly.

**Comment by GrumpyOldPizza** [comment]
No, I have no idea. You probably have to port the libray in question and
pick the appropriate pins.
