### ISSUE TITLE
Is it possivle to work with I2S? 

### ISSUE THREAD

**Issue by diegocabral1988** [GrumpyOldPizza/arduino-STM32L4#28]
Could someone please guide me on how to make the I2S protocol work with the ICS43434 (MEMS Microphone) so I could use a FFT to get the frequency domain. And after that apply the perseval theorem to get the dB measurement of that signal.

ps: I think the Hamming window will be used.

**Comment by kriswiner** [comment]
Start with this:

https://www.arduino.cc/en/Reference/ArduinoSound
