### ISSUE TITLE
STM32F476RE - USB not recognized

### ISSUE THREAD

**Issue by denisn73** [GrumpyOldPizza/arduino-STM32L4#34]
I'm want use ST25R3911B-DISCO board with this core.
Programm downloading and normal working. But USB dsn't work, it not recognized, it no usb enumeration in windows.
I'm try compiling with this and unsuccessfully:
 #define STM32L4_CONFIG_USB_VBUS           GPIO_PIN_NONE
I'm try directly connect 5V to PA9, not happening too.
What can be wrong?

**Comment by GrumpyOldPizza** [comment]
Have you tried:

#define STM32L4_CONFIG_HSECLK             0

The board you cite is not supported, so not surprising it ain't working ;-)

Which variant did you start with ?

- Thomas

**Comment by denisn73** [comment]
No, but I'll try.
On the board STM32L476RE, respectively, for compilation i use variant "Dragonfly"
USB circuitry differs only in the absence of VBUS and ID lines

**Comment by denisn73** [comment]
Tried this settings and nothing has changed:
> #define STM32L4_CONFIG_LSECLK             0 // 32768
> #define STM32L4_CONFIG_HSECLK             0 // 16000000
> #define STM32L4_CONFIG_SYSOPT             0 // SYSTEM_OPTION_VBAT_CHARGING
> #define STM32L4_CONFIG_USB_VBUS           GPIO_PIN_NONE // GPIO_PIN_PA9

**Comment by denisn73** [comment]
Added a pull-up resistor to the USB_DP line as well as on boards with STM32F103 and it worked! =))

**Comment by GrumpyOldPizza** [comment]
You need to keep STM32L4_CONFIG_LSECLK 32768

**Comment by denisn73** [comment]
I'm known, already keep it and creat separate board variant with pin names

**Comment by GrumpyOldPizza** [comment]
Right, but there is no external pullup required. If so, something else is
badly wrong. STM32L476 has a builtin pullup.
