### ISSUE TITLE
Ladybug MSC/DOSFS

### ISSUE THREAD

**Issue by flybrianfly** [GrumpyOldPizza/arduino-STM32L4#45]
I'd like to use USB/MSC with the Ladybug and a SD card on an SPI interface. I must be missing something fairly trivial since I'm not able to get this to work. Are there any examples for this functionality?

Thanks!
Brian

**Comment by kriswiner** [comment]
Need a bit more information here, what are the connections and what does
"can't get it to work" mean?

**Comment by flybrianfly** [comment]
Thanks for the quick reply. Connections are CLK to pin13, MOSI to pin 12, MISO to pin 11, and CS to pin 10. Power and ground from the Ladybug GND and VIN. I'm not able to get the SD to show up as a mass storage device on Windows.

**Comment by kriswiner** [comment]
Did you select usb + mass srorage device and sd card in the tools dropdown
menu?
