### ISSUE TITLE
openocd binary linked to 32-bit version of libudev

### ISSUE THREAD

**Issue by kaofishy** [GrumpyOldPizza/arduino-STM32L4#9]
When running on 64-bit Fedora Linux 25 and attempting to flash NUCLEO-L432KC using the STLink-v2 option in Arduino IDE, it fails saying that openocd cannot find libudev.so.1. It turns out that the binary is looking for the 32-bit version of the library which is not installed by default. After installing the 32-bit version of the library (systemd-libs) openocd was able to execute.

I don't know the proper solution to this, add an instruction to tell users to install the 32-bit library? Include both 32-bit and 64-bit versions of openocd?

**Comment by GrumpyOldPizza** [comment]
That is correct. Only the 32 bit version on openocd is in use.
